# ░█████╗░░█████╗░░█████╗░██╗░░░░░██╗░░░░░░█████╗░██████╗░██████╗░██╗░░░██╗
# ██╔══██╗██╔══██╗██╔══██╗██║░░░░░██║░░░░░██╔══██╗██╔══██╗██╔══██╗╚██╗░██╔╝
# ██║░░╚═╝██║░░██║██║░░██║██║░░░░░██║░░░░░██║░░██║██████╦╝██████╦╝░╚████╔╝░
# ██║░░██╗██║░░██║██║░░██║██║░░░░░██║░░░░░██║░░██║██╔══██╗██╔══██╗░░╚██╔╝░░
# ╚█████╔╝╚█████╔╝╚█████╔╝███████╗███████╗╚█████╔╝██████╦╝██████╦╝░░░██║░░░
# ░╚════╝░░╚════╝░░╚════╝░╚══════╝╚══════╝░╚════╝░╚═════╝░╚═════╝░░░░╚═╝░░░

# Developer / Разработчик: ILeZzoV

# Socials / Ссылки:
# • Contact with me / Связаться: https://t.me/ilezovofficial
# • Telegram Channel / Телеграм канал: https://t.me/ilezzov
# • GitHub: https://github.com/ilezzov-code

# Plugin Pages / Страницы плагинов:
# • GitHub: https://github.com/ilezzov-code/CoolLobby
# • Modrinth: soon
# • Spigot: soob
# • CurseForge: soon
# • Hangar: soon

# By me coffee / Поддержать разработчика:
# • DA: https://www.donationalerts.com/r/ilezzov_dev
# • YooMoney: https://yoomoney.ru/to/4100118180919675
# • Telegram Gift: https://t.me/ilezovofficial
# • TON: UQCInXoHOJAlMpZ-8GIHqv1k0dg2E4pglKAIxOf3ia5xHmKV
# • BTC: 1KCM1QN9TNYRevvQD63UF81oBRSK67vCon
# • Card: 5536914188326494

# Supporting messages languages / Доступные языки сообщений:
# • Русский (ru-RU)
# • English (en-US)
language: "ru-RU"

# Check the plugin for updates
# Проверять плагин на наличие обновлений
check_updates: true

lobby_settings:
  # The names of the lobby worlds
  # Имя lobby мира
  worlds:
    - world
    - lobby-1
    - lobby-2

  # Disable damage
  # Отключить получение урона
  disable_damage: true

  # Disable hunger
  # Отключить голод
  disable_hunger: true

  # Disable daylight cycle
  # Отключить смены времени суток
  disable_daylight_cycle: true

  # Disable mob spawning
  # Отключить спавн мобов
  disable_mob_spawning: true

  # Disable fire tick
  # Отключить распространение огня
  disable_fire_tick: true

  # Disable weather cycle
  # Отключить смену погоды
  disable_weather_cycle: true

  # Default time value
  # Стандартное время суток
  default_time:
    enable: true
    value: 1000

  # Default weather
  # Стандартная погода
  default_weather:
    enable: true
    type: CLEAR # CLEAR, RAIN, THUNDER

  # Default gamemode
  # Стандартный игровой режим
  default_gamemode:
    enable: true
    type: ADVENTURE

  # Player XP Level
  # Уровень игрока
  default_level:
    enable: true
    level: 2025

# /firework command. Permission: coollobby.fw
# /firework команда. Права: coollobby.fw
fw_command:
  # Enable the command / Включить команду
  enable: true
  # Use command only lobby world
  only_lobby: true
  # Cooldown command in seconds / Задержка на использование в секундах
  cooldown: 10

# /lighting command. Permission: coollobby.lt
# /lighting команда. Права: coollobby.lt
lt_command:
  # Enable the command / Включить команду
  enable: true
  # Use command only lobby world
  only_lobby: true
  # Cooldown command in seconds / Задержка на использование в секундах
  cooldown: 10

# /spit command. Permission: coollobby.spit
# /spit команда. Права: coollobby.spit
spit_command:
  # Enable the command / Включить команду
  enable: true
  # Use command only lobby world
  only_lobby: true
  # Cooldown command in seconds / Задержка на использование в секундах
  cooldown: 10

# /fly command. Permission: coollobby.fly
# /fly команда. Права: coollobby.fly
fly_command:
  # Enable the command / Включить команду
  enable: true
  # Use command only lobby world
  only_lobby: true
  # Cooldown command in seconds / Задержка на использование в секундах
  cooldown: 10
# Join actions
# Действия при входе игрока
player_join:
  # Enable join message / Включить сообщение при входе
  join_message:
    enable: true
  # Enable global join message / Включить глобальное сообщение при входе
  global_join_message:
    enable: true
  # Join Title / Сообщение на экран при входе
  join_title:
    enable: true
    fade_in: 1 # Time when the title appeared in seconds / Время появления текста в секундах
    fade_out: 1 # Time when the title disappeared in seconds / Время исчезновения текста в секундах
    stay: 5 # Stay time in milliseconds / Время пребывания в миллисекундах
  # Join sound / Звук при входе
  join_sound:
    enable: true
    sound: ENTITY_EXPERIENCE_ORB_PICKUP

# Leave actions
# Действия при выходе игрока
player_leave:
  # Enable global leave message / Включить глобальное сообщение о выходе игрока
  global_leave_message:
    enable: true

# Double Jump
# Двойной прыжок
double_jump:
  enable: true
  cooldown: 10
  # Use double jump only lobby world
  only_lobby: true
  double_jump_sound:
    enable: true
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
  double_jump_particle:
    enable: true
    particle: FLAME

# Don't edit this
# Не редактируйте это
config_version: 1.0




